# Generated by Django 6.0.3 on 2026-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
